package org.iets3.core.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import org.jetbrains.mps.openapi.model.SNode;
import org.iets3.core.base.behavior.IContainsStuffToRunManually__BehaviorDescriptor;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.iets3.core.base.behavior.ICanRunCheckManually__BehaviorDescriptor;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.ide.editor.MPSEditorDataKeys;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import de.slisson.mps.hacks.editor.EditorComponentHacks;
import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.internal.collections.runtime.IVisitor;

public class runManuallyOnContainer_Action extends BaseAction {
  private static final Icon ICON = IconContainer.ICON_a0_2;

  public runManuallyOnContainer_Action() {
    super("Run/Evaluate/Check Children Manually", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setExecuteOutsideCommand(false);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public boolean isApplicable(AnActionEvent event, final Map<String, Object> _params) {
    Iterable<SNode> manuallyRunNodes = IContainsStuffToRunManually__BehaviorDescriptor.manuallyRunNodes_idTuTPrvRoDG.invoke(event.getData(MPSCommonDataKeys.NODE));
    if (manuallyRunNodes == null) {
      return false;
    }
    return Sequence.fromIterable(manuallyRunNodes).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (boolean) ICanRunCheckManually__BehaviorDescriptor.mustBeRunManually_id3R3AIvumAZH.invoke(it) && (boolean) ICanRunCheckManually__BehaviorDescriptor.readyToRunManually_id3R3AIvumwpv.invoke(it);
      }
    });
  }
  @Override
  public void doUpdate(@NotNull AnActionEvent event, final Map<String, Object> _params) {
    this.setEnabledState(event.getPresentation(), this.isApplicable(event, _params));
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      SNode node = event.getData(MPSCommonDataKeys.NODE);
      if (node != null && !(SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getInterfaceConcept(0x7b68d745a7b848b9L, 0xbd9c05c0f8725a35L, 0xe5ee756dfdd8a45L, "org.iets3.core.base.structure.IContainsStuffToRunManually")))) {
        node = null;
      }
      if (node == null) {
        return false;
      }
    }
    {
      EditorContext p = event.getData(MPSEditorDataKeys.EDITOR_CONTEXT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    Iterable<SNode> manuallyRunNodes = IContainsStuffToRunManually__BehaviorDescriptor.manuallyRunNodes_idTuTPrvRoDG.invoke(event.getData(MPSCommonDataKeys.NODE));
    for (SNode mrn : Sequence.fromIterable(manuallyRunNodes)) {
      ICanRunCheckManually__BehaviorDescriptor.runManually_id3R3AIvumrTm.invoke(mrn, event.getData(MPSEditorDataKeys.EDITOR_CONTEXT));
    }
    event.getData(MPSEditorDataKeys.EDITOR_CONTEXT).getEditorComponent().update();
    final SNode cr = SNodeOperations.getContainingRoot(event.getData(MPSCommonDataKeys.NODE));
    ListSequence.fromList(EditorComponentHacks.findAllInstances()).where(new IWhereFilter<EditorComponent>() {
      public boolean accept(EditorComponent it) {
        return it.getRootCell().getSNode() == cr;
      }
    }).visitAll(new IVisitor<EditorComponent>() {
      public void visit(EditorComponent it) {
        it.update();
      }
    });
  }
}
