package org.iets3.core.users.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a0a = new IconResource("user.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a0b = new IconResource("userDirectory.png", IconContainer.class);
}
