package org.iets3.ears.gxw.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PropositionalFormulaSR_Constraints extends BaseConstraintsDescriptor {
  public PropositionalFormulaSR_Constraints() {
    super(MetaAdapterFactory.getInterfaceConcept(0x7731a166da1f472eL, 0xa40a2283f5e47dc5L, 0x5d97a5a869295cc2L, "org.iets3.ears.gxw.structure.PropositionalFormulaSR"));
  }

}
