package org.iets3.core.base.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import org.iets3.core.base.behavior.ICanRunCheckManually__BehaviorDescriptor;
import org.iets3.core.base.behavior.ICanStoreCheckResult__BehaviorDescriptor;
import org.iets3.core.base.behavior.IResult;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class typeof_ICanRunCheckManually_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_ICanRunCheckManually_InferenceRule() {
  }
  public void applyRule(final SNode icrm, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if ((boolean) ICanRunCheckManually__BehaviorDescriptor.mustBeRunManually_id3R3AIvumAZH.invoke(icrm)) {
      if ((boolean) ICanStoreCheckResult__BehaviorDescriptor.hasExistingResult_id3R3AIvumwpO.invoke(icrm)) {
        IResult res = ICanStoreCheckResult__BehaviorDescriptor.getLastResult_id3R3AIvumwq7.invoke(icrm);
        if (res != null) {
          if (!(res.isOk()) && (boolean) ICanRunCheckManually__BehaviorDescriptor.highlightError_id4b4fYXfo1HZ.invoke(icrm)) {
            {
              MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(icrm, "[MANUALLY CHECKED] " + res.getErrorMessage(), "r:e5a2b77c-569f-4c13-8679-6ec5a6000fa9(org.iets3.core.base.typesystem)", "4450571177430989755", null, errorTarget);
            }
          }
        }
      }
      if ((boolean) ICanRunCheckManually__BehaviorDescriptor.canDetectChange_id6MJy$PGsBY8.invoke(icrm)) {
        if ((boolean) ICanRunCheckManually__BehaviorDescriptor.hasChangedAndMustBeRechecked_id6MJy$PGsBKB.invoke(icrm)) {
          {
            MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning(icrm, "This code has changed; check must be run manually", "r:e5a2b77c-569f-4c13-8679-6ec5a6000fa9(org.iets3.core.base.typesystem)", "7831630342157144425", null, errorTarget);
          }
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return MetaAdapterFactory.getInterfaceConcept(0x7b68d745a7b848b9L, 0xbd9c05c0f8725a35L, 0x3dc39ae7de59be3aL, "org.iets3.core.base.structure.ICanRunCheckManually");
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
}
