package org.iets3.flow.core.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class NodeCreationPropertyFactory {
  public static class NodeFactory_1235726657816721513 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      SLinkOperations.setTarget(SLinkOperations.getTarget(newNode, MetaAdapterFactory.getContainmentLink(0xe8ac6d1264b24478L, 0xbf9a80cbf4ec8c16L, 0x56e0c2409a3d52dbL, 0x11262ed91ea3974cL, "sourceProperty")), MetaAdapterFactory.getReferenceLink(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x24b2bf7ce1a42fa0L, 0x24b2bf7ce1a42fa1L, "conceptDeclaration"), SLinkOperations.getTarget(SNodeOperations.cast(enclosingNode, MetaAdapterFactory.getConcept(0xe8ac6d1264b24478L, 0xbf9a80cbf4ec8c16L, 0x11262ed91e9e6cf8L, "org.iets3.flow.core.structure.NodeCreationProperty")), MetaAdapterFactory.getReferenceLink(0xe8ac6d1264b24478L, 0xbf9a80cbf4ec8c16L, 0x11262ed91e9e6cf8L, 0x11262ed91ea1252dL, "conceptToBeCreated")));
    }
  }
}
