package org.iets3.core.base.editor;

/*Generated by MPS */

import java.awt.Color;
import jetbrains.mps.openapi.editor.style.StyleRegistry;
import jetbrains.mps.nodeEditor.MPSColors;

public class IETS3Colors {
  public static Color KEYWORD = StyleRegistry.getInstance().getSimpleColor(MPSColors.DARK_BLUE);
  public static Color TYPE = new Color(0, 115, 191);

}
