package org.iets3.table.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Cell = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Content = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Header = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Row = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Table = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Cell;
      case 1:
        return props_Content;
      case 2:
        return props_Header;
      case 3:
        return props_Row;
      case 4:
        return props_Table;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
