package org.iets3.flow.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a0b = new IconResource("F.png", IconContainer.class);
}
